title: Philip Cole Johnson
description: Developer

url: http://philipj.me
baseurl: ""
paginate_path: "blog/page:num/"
permalink: blog/:title/

markdown: kramdown
highlighter: rouge
gems: [jekyll-paginate]
paginate: 5

navigation:
 - title: Home
   url: /index.html
 - title: About
   url: /about
 - title: Contact
   url: /contact

social:
   github: philipcolejohnson
   twitter: brianmaierjr
   facebook: philipcolejohnson
   email: phil@philip.me

google_analytics: "UA-58263416-1"
