title: Philip Cole Johnson
description: Developer, Writer

url: http://philipj.me
baseurl: ""
paginate_path: "blog/page:num/"
permalink: blog/:title/

markdown: kramdown
highlighter: rouge
gems: [jekyll-paginate]
paginate: 5

navigation:
 - title: Home
   url: /
 - title: About
   url: /about
 - title: Contact
   url: /contact

social:
   github: philipcolejohnson
   facebook: philipcolejohnson
   email: hi@philipj.me

google_analytics: "GTM-K49223"
